name: Publish Release

on:
  workflow_dispatch:
  push:
    branches:
      - 'slygo'

defaults:
  run:
    working-directory: cmd/aries-js-worker

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: npm ci
        working-directory: cmd/aries-js-worker
      - uses: scaffoldly/bump-version-action@v1
        with:
          action: prerelease
          version-file: cmd/aries-js-worker/package.json
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
